defmodule AshTest.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:habits) do
      modify :player_id, :binary_id, null: false
    end
  end

  def down do
    alter table(:habits) do
      modify :player_id, :binary_id, null: true
    end
  end
end