defmodule AshTest.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:players, primary_key: false) do
      add :id, :binary_id, null: false, primary_key: true
      add :username, :text, null: false
    end

    create table(:habits, primary_key: false) do
      add :id, :binary_id, null: false, primary_key: true
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :public, :boolean, null: false, default: false
      add :player_id, references("players", type: :binary_id, column: :id)
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :body, :text, null: false
    end
  end

  def down do
    drop table("habits")

    drop table("players")
  end
end